AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Basic CloudFormation template to launch a single EC2 instance in the default VPC and default subnet.
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      # Use an Amazon Linux 2023 AMI us-east-1 Region (update AMI ID per region!)
      ImageId: ami-0532be01f26a3de55
      InstanceType: t2.micro   # Define Instance Type
      # By not specifying a SubnetId, EC2 will launch in the default subnet
      # By not specifying the Security Group, EC2 will launch with the default Security Group
      Tags:
        - Key: Name
          Value: MyFirstCFNInstance
